config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :spaces do
    resources :memberships
    resources :posts
  end

  resources :posts do
    resources :comments
  end

  root to: 'home#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :user
  has_many :memberships
  has_many :users, through: :memberships, as: :members

  has_many :posts

  def posts_count_text
    case posts.length
    when 0
      return 'No posts yet'
    when 1
      return 'One post'
    else
      return "#{ posts.length } posts"
    end
  end

  def can_user_post_here(user_id)
    users.where(id: user_id).present? || user.id == user_id
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /spaces
  # GET /spaces.json
  def index
    @spaces = Space.order('updated_at desc')
  end

  # GET /spaces/1
  # GET /spaces/1.json
  def show
  end

  # GET /spaces/new
  def new
    @space = Space.new

    respond_to do |format|
      format.js
      format.html { redirect_to spaces_path }
    end
  end

  # GET /spaces/1/edit
  def edit
  end

  # POST /spaces
  # POST /spaces.json
  def create
    @space = Space.new(space_params)

    @space.user = current_user

    respond_to do |format|
      # if @space.save
      #   format.html { redirect_to spaces_path, notice: 'Space was successfully created.' }
      #   format.json { render :show, status: :created, location: @space }
      # else
      #   format.html { render :new }
      #   format.json { render json: @space.errors, status: :unprocessable_entity }
      # end
      format.js
    end
  end

  # PATCH/PUT /spaces/1
  # PATCH/PUT /spaces/1.json
  def update
    respond_to do |format|
      if @space.update(space_params)
        format.html { redirect_to @space, notice: 'Space was successfully updated.' }
        format.json { render :show, status: :ok, location: @space }
      else
        format.html { render :edit }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spaces/1
  # DELETE /spaces/1.json
  def destroy
    @space.destroy
    respond_to do |format|
      format.html { redirect_to spaces_url, notice: 'Space was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_space
      @space = Space.find(params[:id]).decorate
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def space_params
      params.require(:space).permit(:name, :user_id)
    end
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/spaces/_form.html.erb
<%= form_for(space, remote: true) do |f| %>
  <% if space.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(space.errors.count, "error") %> prohibited this space from being saved:</h2>

      <ul>
      <% space.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mdl-textfield mdl-js-textfield">
    <%= f.text_field :name, class: "mdl-textfield__input" %>
    <%= f.label :name, class: "mdl-textfield__label" %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= current_user.name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spaces/_new.html.erb
<h4 class="mdl-dialog__title mdl-dialog-title">New Space</h4>

<%= form_for(@space, remote: true) do |f| %>
    <div class="mdl-dialog__content mdl-dialog-content">
    <% if @space.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@space.errors.count, "error") %> prohibited this space from being saved:</h2>
    
        <ul>
            <% @space.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </div>
    <% end %>
    
    <div class="mdl-card__supporting-text">
        <div class="mdl-textfield mdl-js-textfield">
            <%= f.text_field :name, class: "mdl-textfield__input" %>
            <%= f.label :name, class: "mdl-textfield__label", for: "space_name" %>
        </div>
    </div>
    
</div>
<div class="mdl-dialog__actions mdl-dialog-actions">
    <%= button_to "Create", @space, :class => "mdl-button mdl-js-button mdl-button--raised mdl-button--colored", :remote => true  %>
    
    <%= link_to "Cancel", '#', :class => "mdl-button mdl-js-button mdl-button--raised", :onclick => "$(this).closest('.mdl-cell').remove(); return false;"  %>
    <!-- <button type="button" class="mdl-button">Agree</button>
    <button type="button" class="mdl-button close">Disagree</button> -->
</div>
<% end %>

app/views/spaces/_spacemenu.html.erb
<!--<a class="mdl-navigation__link" href="">Link</a> -->
<% Space.where(:user => current_user).order('updated_at desc').each do |space| %>
    <%= link_to space.name, space, class: "mdl-navigation__link" %>
<% end %>

app/views/spaces/create.js.erb
alert("CREATED");

app/views/spaces/edit.html.erb
<h1>Editing Space</h1>

<%= render 'form', space: @space %>

<%= link_to 'Show', @space %> |
<%= link_to 'Back', spaces_path %>

app/views/spaces/index.html.erb
<% content_for :title, "My Spaaaces" %>

<div class="mdl-grid" id="spaces">
  <% @spaces.each do |space| %>
  <div class="mdl-cell mdl-cell--4-col">
    <div class="mdl-card mdl-shadow--4dp">
      <div class="mdl-card__title mdl-card--expand">
        <h2 class="mdl-card__title-text"><%= space.name %></h2>
      </div>
      <div class="mdl-card__supporting-text">
        <div><%= space.user.name %></div>
        <div><%= space.posts_count_text %></div>
      </div>
      <div class="mdl-card__actions mdl-card--border">
        <%= link_to "Open", space, :class => "mdl-button mdl-js-button mdl-button--colored" %>
      </div>
    </div>
  </div>
  <% end %>
</div>


  <%= link_to new_space_path, :class => 'mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored floating_button', :remote => true do %>
  <i class="material-icons">add</i>
  <% end %>

app/views/spaces/new.js.erb
'use strict';

(function(){
  console.log("SHOWING MODAL");
  const dialog = document.querySelector('#dialog');

  console.log("DIAKLOG FOUND>?", dialog);

  // console.log("IS THERE A HTML?", dialog.html);
  // debugger;
  dialog.innerHTML = "<%= escape_javascript(render partial: 'new') %>";


  console.log("IS THERE A SHOWMODAL?", dialog.showModal);

  dialog.showModal();  
})();

app/views/spaces/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="mdl-grid" id="posts">
  <div class="mdl-cell mdl-cell--12-col">
    <h2><%= @space.name %></h2>
    <h6>Created by <%= @space.user.name %></h6>
  </div>
<% @space.posts.each do |post| %>
  <%= render "posts/show", post: post %>
<% end %>
</div>


<%= link_to new_post_path(:space_id => @space.id), :class => 'mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored floating_button', :remote => true do %>
  <i class="material-icons">add</i>
<% end %>