config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :spaces do
    resources :memberships
    resources :posts
  end

  resources :posts do
    resources :comments
  end

  root to: 'home#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :space
  belongs_to :user
  
  validates :link, url: true

  before_save :fill_metadata

  private

  def fill_metadata
    set_metadata if self.title.nil? || self.description.nil? || self.image.nil?
  end

  def set_metadata
    page = MetaInspector.new(self.link)
    self.title = page.title
    self.description = page.description
    self.image = page.images.best
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new

    @post.space = get_space

    if (@post.space.nil?)
      redirect_to spaces_path
    end

    respond_to do |format|
      format.js
      format.html  { render js }
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post.space, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.js { render action: :new }
        format.html { render js, action: :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id]).decorate
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:link, :space_id).merge(user_id: current_user.id)
    end

    def get_space
      space = Space.find(params[:space_id])
    end

    def can_user_post_here
      
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link %>
    <%= f.text_field :link %>
  </div>

  <div class="field">
    <%= f.label :space_id %>
    <%= f.text_field :space_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_new.html.erb
<div class="mdl-cell mdl-cell--12-col">

    <div class="mdl-card mdl-shadow--2dp mdl-card-wide">
      <div class="mdl-card__title">
        <h2 class="mdl-card__title-text">New Post</h2>
      </div>
        <%= form_for(@post, remote: true) do |f| %>
      <div class="mdl-card__supporting-text">
            <% if @post.errors.any? %>
                <div id="error_explanation">
                <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

                <ul>
                <% @post.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
                </ul>
                </div>
            <% end %>

            <div class="field">
                <%= f.label :link %>
                <%= f.text_field :link %>
            </div>

            <%= f.hidden_field :space_id %>
      </div>
      <div class="mdl-card__actions mdl-card--border">
        <%= button_to "Create", @post, :class => "mdl-button mdl-js-button mdl-button--raised mdl-button--colored", :remote => true  %>
        <%= link_to "Cancel", '#', :class => "mdl-button mdl-js-button mdl-button--raised", :onclick => "$(this).closest('.mdl-cell').remove(); return false;"  %>
      </div>
      <% end %>
    </div>

  </div>

app/views/posts/_show.html.erb
<div class="mdl-cell mdl-cell--12-col">
  <div class="mdl-card mdl-shadow--2dp mdl-card-wide">
    <div class="mdl-card__title" style="<%= post.background_image_style %>">
      <h2 class="mdl-card__title-text"><%= post.title || post.link %></h2>
    </div>
    <div class="mdl-card__supporting-text">
      <%= post.description %>
    </div>
    <div class="mdl-card__actions mdl-card--border">
      <%= link_to "Open Link", post.link, target: "_blank", class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>
      <%= link_to "Comments", space_post_url(post.space, post), class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Space</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.link %></td>
        <td><%= post.space %></td>
        <td><%= post.user %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.js.erb
$("#posts").html("<%= escape_javascript(render controller: 'post', partial: 'new') %>"); 

app/views/posts/show.html.erb
<!--
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @post.link %>
</p>

<p>
  <strong>Space:</strong>
  <%= @post.space %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
-->

<div class="mdl-cell mdl-cell--12-col">
  <div class="mdl-card mdl-shadow--2dp mdl-card-wide">
    <div class="mdl-card__title" style="<%= @post.background_image_style %>">
      <h2 class="mdl-card__title-text"><%= @post.title %></h2>
    </div>
    <div class="mdl-card__supporting-text">
      <%= @post.description %>
    </div>
    <!-- <div class="mdl-card__actions mdl-card--border">
      <%= link_to "Open Post", space_post_url(@post.space, @post), class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>
    </div> -->
  </div>
</div>